### ISSUE TITLE
Mac MathExtension error with MacTex

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [Zen-Reportz/zen_knit#19]
I recieve the error `TypeError: MathExtension.extendMarkdown() missing 1 required positional argument: 'md_globals'`

when attempting to knit the following file:

````
---
date: CURRENT_DATE
output:
    format: html
    html:
        css: skleton
---

# Header
Text

```{run=true, echo=true, render=true}
print(2)
```
````

* I pip installed zen-knit into a conda environment, brew installed pandoc, and installed MacTex via the pkg installer.
* MacOS 12.4

Any suggestions for what might be going wrong?

**Comment by contactzen** [comment]
Hello @marcel-goldschen-ohm ,

Thank you for reaching out. 

zen_knit is using texlive letax package. Have you tried to installing that package ?

Here is instruction on how to install it in mac
 https://tug.org/texlive/quickinstall.html

**Comment by contactzen** [comment]
@marcel-goldschen-ohm , I am closing this ticket, please let me know if you still experiencing problem once installing texlive.
